// <auto-generated />
namespace RPA.ClaimStatements.Generator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EFAonXB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EFAonXB));
        
        string IMigrationMetadata.Id
        {
            get { return "201810081307238_EFAonXB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
